import os
from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from langchain_chroma import Chroma
from langchain_core.prompts import ChatPromptTemplate
from langchain_classic.chains.retrieval import create_retrieval_chain
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from src.config import EMBEDDING_MODEL, LLM_MODEL, DB_PATH, RETRIEVAL_K


# Retrieves context from ChromaDB and returns an answer generated by Gemini.
def answer_question(user_query: str, db_path: str = DB_PATH) -> dict:
    if not os.path.exists(db_path):
        raise FileNotFoundError(
            f"Vector store not found at '{db_path}'. Please run ingestion first!"
        )

    # 1. Load Vector Store
    embeddings = GoogleGenerativeAIEmbeddings(model=EMBEDDING_MODEL)
    vector_db = Chroma(persist_directory=db_path, embedding_function=embeddings)
    retriever = vector_db.as_retriever(search_kwargs={"k": RETRIEVAL_K})

    llm = ChatGoogleGenerativeAI(model=LLM_MODEL)

    # "you don't know. Do not hallucinate.\n\n"
    system_prompt = (
        "You are a helpful assistant for question-answering tasks.\n"
        "Use the following pieces of retrieved context to answer the question.\n"
        "If you don't know the answer or if it is not present in the context, say "
        '"I don\'t know based on the provided document."\n'
        "Do not use outside knowledge.\n"
        "Keep the answer concise and clear.\n\n"
        "Retrieved context:\n{context}"
    )

    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", system_prompt),
            ("human", "{input}"),
        ]
    )

    # 3. Build & Run Chain
    question_answer_chain = create_stuff_documents_chain(llm, prompt)
    rag_chain = create_retrieval_chain(retriever, question_answer_chain)

    return rag_chain.invoke({"input": user_query})
